### ISSUE TITLE
The service compiler doesn't allow String as the element type of List

### ISSUE THREAD

**Issue by smanilov** [dartino/sdk#235]
For an input like

```
service Foo {}
struct Bar {
    List<String> baz;
}
```

The compiler prints an error like

```
stderr:
InternalCompilerError: Original error:
type 'StringType' is not a subtype of type 'SimpleType' of 'elementType'.
#0      ListType.ListType (package:old_servicec/src/parser.dart:153:17)
#1      Converter.convertType (package:servicec/converter.dart:113:18)
#2      Converter.visitField (package:servicec/converter.dart:102:21)
#3      FieldNode.accept (package:servicec/node.dart:100:13)
#4      RecursiveVisitor.visitStruct (package:servicec/node.dart:266:14)
#5      Converter.visitStruct (package:servicec/converter.dart:59:22)
#6      StructNode.accept (package:servicec/node.dart:55:13)
#7      RecursiveVisitor.visitCompilationUnit (package:servicec/node.dart:252:16)
#8      Converter.visitCompilationUnit (package:servicec/converter.dart:34:31)
#9      convert (package:servicec/converter.dart:26:13)
#10     compileInput.<compileInput_async_body> (package:servicec/compiler.dart:78:19)
#11     Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
#12     _rootRun (dart:async/zone.dart:900)
#13     _CustomZone.run (dart:async/zone.dart:803)
#14     _CustomZone.runGuarded (dart:async/zone.dart:709)
#15     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:734)
#16     _rootRun (dart:async/zone.dart:904)
#17     _CustomZone.run (dart:async/zone.dart:803)
#18     _CustomZone.runGuarded (dart:async/zone.dart:709)
#19     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:734)
#20     _microtaskLoop (dart:async/schedule_microtask.dart:43)
#21     _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#22     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:394)
#23     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

#0      compileInput.<compileInput_async_body> (package:servicec/compiler.dart:85:7)
#1      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
#2      _rootRun (dart:async/zone.dart:900)
#3      _CustomZone.run (dart:async/zone.dart:803)
#4      _CustomZone.runGuarded (dart:async/zone.dart:709)
#5      _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:734)
#6      _rootRun (dart:async/zone.dart:904)
#7      _CustomZone.run (dart:async/zone.dart:803)
#8      _CustomZone.runGuarded (dart:async/zone.dart:709)
#9      _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:734)
#10     _microtaskLoop (dart:async/schedule_microtask.dart:43)
#11     _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#12     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:394)
#13     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

This input is valid and should be allowed.

**Comment by zerny** [comment]
The idl format as implemented now is not meant to support List<String>. List<T> is only valid if T is a primitive (which does not include String) or a struct. We should produce a friendly error for this case and remove the inclusion of "String" in the IDL spec.
