### ISSUE TITLE
`dartino build` fails on a clean install of ubuntu

### ISSUE THREAD

**Issue by mit-mit** [dartino/sdk#436]
1. Install ubunto
2. Follow getting started
3. The `dartino build` step fails:

```
mit@uvm:~/dartino-sdk$ dartino build samples/general/hello.dart
STDOUT:

STDERR:
/home/mit/dartino-sdk/platforms/stm32f746g-discovery/bin/link.sh: 44: /home/mit/dartino-sdk/platforms/stm32f746g-discovery/bin/link.sh: Syntax error: "(" unexpected

Internal error: Failed to build image, error = 2
#0      throwInternalError (package:dartino_compiler/src/diagnostic.dart:206:3)
#1      buildImage.<buildImage_async_body> (package:dartino_compiler/src/worker/developer.dart:1256:7)
#2      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:27)
#3      _rootRunUnary (dart:async/zone.dart:914)
#4      _CustomZone.runUnary (dart:async/zone.dart:810)
#5      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:551)
#6      _Future._propagateToListeners (dart:async/future_impl.dart:637)
#7      _Future._completeWithValue (dart:async/future_impl.dart:424)
#8      Future.wait.<anonymous closure> (dart:async/future.dart:299)
#9      _rootRunUnary (dart:async/zone.dart:914)
#10     _CustomZone.runUnary (dart:async/zone.dart:810)
#11     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:551)
#12     _Future._propagateToListeners (dart:async/future_impl.dart:637)
#13     _Future._completeWithValue (dart:async/future_impl.dart:424)
#14     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:479)
#15     _rootRun (dart:async/zone.dart:907)
#16     _CustomZone.run (dart:async/zone.dart:802)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:735)
#18     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#19     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#20     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

mit@uvm:~/dartino-sdk$ 

```

**Comment by mit-mit** [comment]
Tracking in #438  and #437
