### ISSUE TITLE
Error message for trying to prepare a bleed edge pi-image makes no sense

### ISSUE THREAD

**Issue by lukechurch** [dartino/sdk#459]
```
lukechurch-macbookpro:raspberry-pi2 lukechurch$ ./flash-sd-card --version 0.4.0-edge.a366efe0b5d4d1a69051d66cd8cba58be2881b29
This program requires superuser to run.
This program will prepare an SD card for Dartino on the Raspberry Pi 2.
WARNING: For bleeding edge a fixed image is used.
Please remove all SD cards from this computer. Then press Enter.
Please insert the SD card you want to use with Dartino. Then press Enter.

Found the SD card /dev/rdisk3.
/dev/disk3 (internal, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:     FDisk_partition_scheme                        *7.9 GB     disk3
   1:             Windows_FAT_32 boot                    58.7 MB    disk3s1
   2:                      Linux                         4.3 GB     disk3s2

This will delete all contents on the card. Press Enter to use this card (Ctrl-C to cancel).
Enter the name of the device - default is 'dartinopi' (press Enter to accept): 
Enter the static IP address you would like the device to have. Leave it blank to have it assigned via DHCP: 192.168.1.11
Downloading SD card image.
Downloading: FAILURE: Failed request: Not Found
Downloading: received 0 Mb of 0 MbUnhandled exception:
Instance of 'Failure'
#0      Context.failure.<failure_async_body> (file:///Users/lukechurch/GitRepos/dartino-repo/sdk/pkg/flash_sd_card/lib/src/context.dart:169:5)
#1      _RootZone.runUnary (dart:async/zone.dart:1137)
#2      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:551)
#3      _Future._propagateToListeners (dart:async/future_impl.dart:637)
#4      _Future._complete (dart:async/future_impl.dart:414)
#5      _SyncCompleter.complete (dart:async/future_impl.dart:52)
#6      Context.done.<done_async_body> (file:///Users/lukechurch/GitRepos/dartino-repo/sdk/pkg/flash_sd_card/lib/src/context.dart:79:3)
#7      _RootZone.runUnary (dart:async/zone.dart:1137)
#8      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:551)
#9      _Future._propagateToListeners (dart:async/future_impl.dart:637)
#10     _Future._addListener.<anonymous closure> (dart:async/future_impl.dart:293)
#11     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#12     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#13     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

```

We need something a bit more comprehensible than this stack trace. I suspect it's saying that it can't install download the right image file?

Once we work out what the problem is I'll be happy to draft a message that explains it.

**Comment by sgjesse** [comment]
I am quite sure this is due to the file not being available for download. However it is now (https://storage.googleapis.com/dartino-temporary/channels/be/raw/0.4.0-edge.a366efe0b5d4d1a69051d66cd8cba58be2881b29/sdk/dartino_raspbian.img.zip).

Did you try this soon after the commit of a366efe0b5d4d1a69051d66cd8cba58be2881b29, so that the SDK build might not have had the time to finish.
