### ISSUE TITLE
Incremental compilation sometimes fails compilation

### ISSUE THREAD

**Issue by karlklose** [dartino/sdk#474]
This is the stack trace:

```
    $ out/DebugXARM/dartino compile /b/build/slave/target-dartino-linux-debug-arm/build/sdk/out/DebugXARM/generated_tests/language/async_await_syntax_test_b12c.dart in session 1
     Unexpected element in predecessorSystem.
     #0      DartinoSystemBuilder.computeSystem.<anonymous closure>.<anonymous closure> (package:dartino_compiler/src/dartino_system_builder.dart:1082:13)
     #1      _Leaf._insertWith.insertPair (package:persistent/src/map_impl.dart:200:22)
     #2      _Leaf._insertWith.insertPairs (package:persistent/src/map_impl.dart:218:25)
     #3      _Leaf._insertWith (package:persistent/src/map_impl.dart:231:60)
     #4      _SubMap._insertWith (package:persistent/src/map_impl.dart:475:13)
     #5      _SubMap._insertWith (package:persistent/src/map_impl.dart:475:13)
     #6      _APersistentMap.insert (package:persistent/src/map_impl.dart:63:7)
     #7      DartinoSystemBuilder.computeSystem.<anonymous closure> (package:dartino_compiler/src/dartino_system_builder.dart:1078:47)
     #8      _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:340)
     #9      DartinoSystemBuilder.computeSystem (package:dartino_compiler/src/dartino_system_builder.dart:1077:32)
     #10     DartinoReuser.computeUpdateDartino (package:dartino_compiler/incremental/dartino_reuser.dart:235:42)
     #11     IncrementalCompiler.compileUpdates.<anonymous closure>.<<anonymous closure>_async_body> (package:dartino_compiler/incremental/dartino_compiler_incremental.dart:240:29)
     #12     Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
     #13     _rootRun (dart:async/zone.dart:895)
     #14     _CustomZone.run (dart:async/zone.dart:790)
     #15     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:723)
     #16     _microtaskLoop (dart:async/schedule_microtask.dart:41)
     #17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
     #18     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:394)
     #19     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
     #20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
  
```

**Comment by karlklose** [comment]
This reproduced when relanding https://codereview.chromium.org/1895053004. It seems like this failure is caused by that CL.
