### ISSUE TITLE
The test dartino_tests/debugger_snapshot/step_over_test can fail

### ISSUE THREAD

**Issue by sgjesse** [dartino/sdk#524]
From https://build.chromium.org/p/client.fletch/builders/dartino-mac-release-x86/builds/1231/steps/Test%20ReleaseX64Clang/logs/stdio

Judging from the error message this does not seem to be related to the particular test.

```
FAILED: none-dartino_tests release_x64_clang dartino_tests/debugger_snapshot/step_over_test
Expected: Pass 
Actual: Fail
CommandOutput[dartino_test]:
  stdout:
     step_over_test: tests/debugger/step_over_test.dart
  stderr:
     Bad state: The dartino-vm did not print an address on which it is listening on.
     #0      DartinoVm.start.<start_async_body> (package:dartino_compiler/dartino_vm.dart)
     #1      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:34)
     #2      _rootRunBinary (dart:async/zone.dart:914)
     #3      _CustomZone.runBinary (dart:async/zone.dart:806)
     #4      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:579)
     #5      _Future._propagateToListeners (dart:async/future_impl.dart:641)
     #6      _Future._completeError (dart:async/future_impl.dart:432)
     #7      _Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:488)
     #8      _rootRun (dart:async/zone.dart:895)
     #9      _CustomZone.run (dart:async/zone.dart:790)
     #10     _CustomZone.runGuarded (dart:async/zone.dart:696)
     #11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:721)
     #12     _microtaskLoop (dart:async/schedule_microtask.dart:41)
     #13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
     #14     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
     #15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
     
  exitcode: 0

Command[dartino_test]: DartinoTestCommand(debugger_snapshot/step_over_test)
Took 0:00:02.759649

Short reproduction command (experimental):
    python tools/test.py -mrelease -ax64 --kill-persistent-process=0 --run-gclient-hooks=0 --build-before-testing=0 -rdartino_tests -t60 dartino_tests/debugger_snapshot/step_over_test
```

**Comment by sigurdm** [comment]
I find this failure mysterious, but the cl should help us find out what happened to the dartino vm if it reappears.
