### ISSUE TITLE
Debugger gives exception and hangs when .info file is not found

### ISSUE THREAD

**Issue by sgjesse** [dartino/sdk#525]
Sample output

```
out/ReleaseX64/dartino debug platforms/stm/disco_dartino/src/test.dart on tty /dev/ttyACM0
Using template settings file '/usr/local/prj/dart/github/dartino/sdk/.dartino-settings'
Attached to /dev/ttyACM0
Listening for connection.
InputError(DiagnosticKind.infoFileNotFound, {#{uri}: file:///usr/local/prj/dart/github/dartino/sdk/platforms/stm/disco_dartino/src/test.snapshot})
#0      throwFatalError (package:dartino_compiler/src/diagnostic.dart:279:3)
#1      getInfoFromSnapshotLocation.<getInfoFromSnapshotLocation_async_body> (package:dartino_compiler/src/worker/developer.dart:756:5)
#2      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:27)
#3      _rootRunUnary (dart:async/zone.dart:902)
#4      _CustomZone.runUnary (dart:async/zone.dart:798)
#5      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:551)
#6      _Future._propagateToListeners (dart:async/future_impl.dart:637)
#7      _Future._completeWithValue (dart:async/future_impl.dart:424)
#8      _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:479)
#9      _rootRun (dart:async/zone.dart:895)
#10     _CustomZone.run (dart:async/zone.dart:790)
#11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:723)
#12     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#14     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

**Comment by sigurdm** [comment]
Fixed by https://github.com/dartino/sdk/commit/19ba8a2cba05739f87a93a521223b6a976c21745
