### ISSUE TITLE
Using the 'p' command in the debugger can crash the debugger

### ISSUE THREAD

**Issue by sgjesse** [dartino/sdk#565]
Flashing with debugger support:
```
out/ReleaseX64/dartino flash --debugging-mode samples/stm32f746g-discovery/disco-light.dart
```
And the debugging
```
out/ReleaseX64/dartino debug samples/stm32f746g-discovery/disco-light.dart on tty /dev/ttyACM0
Using template settings file '/usr/local/prj/dart/github/dartino/sdk/.dartino-settings'
Attached to /dev/ttyACM0
Starting session. Type 'help' for a list of commands.

### Process is running. Press Ctrl + \ to interrupt it.
```
Pressing `Ctrl + \` and using `p` crashes the debugger.
```
^\samples/stm32f746g-discovery/disco-light.dart:24:54
24       display.drawLine(w ~/ 2, h ~/ 2, rnd.nextInt(w), rnd.nextInt(h), color);
> p
Closing tty-connection
The Dartino program is broken and has crashed.

The Dartino team would greatly appreciate if you would take a moment to
report this problem at https://github.com/dartino/sdk/issues/new

Please include the following information:

* the name and version of your operating system

* the Dartino SDK version (0.5.0-edge.2004f8c7e9b854a49f495a7f6a9933652a8365b4)

* the entire message you see here (including the full stack trace below)

'package:dartino_compiler/vm_context.dart': Failed assertion: line 933 pos 12: 'response is DartValue' is not true.
#0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
#1      DartinoVmContext.processLocal.<processLocal_async_body> (package:dartino_compiler/vm_context.dart:933:12)
#2      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:27)
#3      _rootRunUnary (dart:async/zone.dart:902)
#4      _CustomZone.runUnary (dart:async/zone.dart:798)
#5      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:551)
#6      _Future._propagateToListeners (dart:async/future_impl.dart:637)
#7      _Future._complete (dart:async/future_impl.dart:414)
#8      _SyncCompleter.complete (dart:async/future_impl.dart:52)
#9      DartinoVmContext.runCommands.<runCommands_async_body> (package:dartino_compiler/vm_context.dart:225:5)
#10     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:27)
#11     _rootRunUnary (dart:async/zone.dart:902)
#12     _CustomZone.runUnary (dart:async/zone.dart:798)
#13     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:551)
#14     _Future._propagateToListeners (dart:async/future_impl.dart:637)
#15     _Future._complete (dart:async/future_impl.dart:414)
#16     _SyncCompleter.complete (dart:async/future_impl.dart:52)
#17     DartinoVmContext.readNextCommand.<readNextCommand_async_body> (package:dartino_compiler/vm_context.dart:278:5)
#18     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:27)
#19     _rootRunUnary (dart:async/zone.dart:902)
#20     _CustomZone.runUnary (dart:async/zone.dart:798)
#21     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:551)
#22     _Future._propagateToListeners (dart:async/future_impl.dart:637)
#23     _Future._complete (dart:async/future_impl.dart:414)
#24     _StreamIteratorImpl._onData (dart:async/stream_impl.dart:1051)
#25     _rootRunUnary (dart:async/zone.dart:902)
#26     _CustomZone.runUnary (dart:async/zone.dart:798)
#27     _CustomZone.runUnaryGuarded (dart:async/zone.dart:704)
#28     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#29     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#30     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:67)
#31     _EventSinkWrapper.add (dart:async/stream_transformers.dart:14)
#32     CommandTransformerBuilder.build.handleData (package:dartino_compiler/src/shared_command_infrastructure.dart:69:16)
#33     _HandlerEventSink.add (dart:async/stream_transformers.dart:216)
#34     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:119)
#35     _rootRunUnary (dart:async/zone.dart:902)
#36     _CustomZone.runUnary (dart:async/zone.dart:798)
#37     _CustomZone.runUnaryGuarded (dart:async/zone.dart:704)
#38     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#39     _DelayedData.perform (dart:async/stream_impl.dart:595)
#40     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:711)
#41     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:671)
#42     _rootRun (dart:async/zone.dart:895)
#43     _CustomZone.run (dart:async/zone.dart:790)
#44     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:723)
#45     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#46     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#47     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#48     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

Session 'local' was terminated.
```

**Comment by sgjesse** [comment]
Seems to depend on the locals on the frame. On some frames this does not happen, and p succeeds, e.g.:
```
^\pkg/stm32/lib/lcd.dart:109:5
109      _lcdSetForegroundColor.icall$1(color.rgb8888);
> p
color: Instance of 'Color'
y2: 256
x2: 366
y1: 136
x1: 240
this: Instance of 'FrameBuffer'
```
