### ISSUE TITLE
Exception when resume from breakpoint

### ISSUE THREAD

**Issue by danrubel** [dartino/sdk#583]
In Atom, 
* open `samples/general/hello.dart`
* set 3 breakpoints
* select `hello.dart` in the run app dropdown
* click the gear to the left of the run app dropdown
* add `debug: true` under `dartino:` in the `hello.yaml` file to enable debugging for this app
* run `hello.dart` in Atom
* when you hit a breakpoint, click the resume button.

On the 2nd resume, this exception occurs...

```
The Dartino program is broken and has crashed.

The Dartino team would greatly appreciate if you would take a moment to
report this problem at https://github.com/dartino/sdk/issues/new

Please include the following information:

* the name and version of your operating system

* the Dartino SDK version (0.5.0-edge.8fee4a1b16ad0cb5dcbcc9a67e23ac7e1fee000f)

* the entire message you see here (including the full stack trace below)

Bad state: Already waiting for next.
#0      _StreamIteratorImpl.moveNext (dart:async/stream_impl.dart:996)
#1      DartinoVmContext.readNextCommand.<readNextCommand_async_body> (package:dartino_compiler/vm_context.dart:248:58)
#2      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
#3      _rootRun (dart:async/zone.dart:895)
#4      _CustomZone.run (dart:async/zone.dart:790)
#5      _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:723)
#6      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#7      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#8      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

Session 'local' was terminated.

exited with code 253
debug session exit code is 253
10 issues1 processgeneral/hello.dart13:6
LFUTF-8Dartdebugging
Plugin status
References
```

**Comment by sgjesse** [comment]
@danrubel Does this also happen int the command-line debugger?
